services:
  - type: web
    name: open5x-backend
    env: python
    rootDir: backend
    buildCommand: "g++ -O3 -o slicer_engine slicer.cpp && pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
