"""exports_f017

Revision ID: 188eaae3020d
Revises: 5ab3716b47bf
Create Date: 2026-09-10 23:29:54.661386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '188eaae3020d'
down_revision: Union[str, Sequence[str], None] = '5ab3716b47bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('dialect', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'BLOCKED', 'FAILED', 'REVOKED', name='exportstatus'), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('export_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status != 'READY' OR storage_uri IS NOT NULL", name='ck_export_ready_storage_uri'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index('ix_export_job_dialect_active', ['job_id', 'dialect'], unique=True, sqlite_where=sa.text("status != 'REVOKED'"), postgresql_where=sa.text("status != 'REVOKED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index('ix_export_job_dialect_active', sqlite_where=sa.text("status != 'REVOKED'"), postgresql_where=sa.text("status != 'REVOKED'"))
    op.drop_table('exports')
    # ### end Alembic commands ###
