"""mesh_metadata

Revision ID: 1d3ea84f6d90
Revises: 81a490f47bde
Create Date: 2026-09-10 19:28:40.287857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3ea84f6d90'
down_revision: Union[str, Sequence[str], None] = '81a490f47bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meshes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('format', sa.Enum('STL_BINARY', name='meshformat'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('triangle_count', sa.Integer(), nullable=False),
    sa.Column('bound_min_x', sa.Float(), nullable=False),
    sa.Column('bound_min_y', sa.Float(), nullable=False),
    sa.Column('bound_min_z', sa.Float(), nullable=False),
    sa.Column('bound_max_x', sa.Float(), nullable=False),
    sa.Column('bound_max_y', sa.Float(), nullable=False),
    sa.Column('bound_max_z', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meshes_content_hash'), 'meshes', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meshes_content_hash'), table_name='meshes')
    op.drop_table('meshes')
    # ### end Alembic commands ###
