"""initial_schema

Revision ID: 59aa2076177a
Revises: 
Create Date: 2026-09-10 19:11:28.527950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59aa2076177a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'OPERATOR', 'VALIDATOR', 'ADMIN', 'SERVICE', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'PARTIAL', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('mode', sa.Enum('THREE_AXIS', 'INDEXED_MULTIDIRECTIONAL', name='jobmode'), nullable=False),
    sa.Column('current_stage', sa.Enum('MESH_VALIDATION', 'CANONICAL_FRAME', 'CHUNK_CONSTRUCTION', 'SECTIONING', 'POLYGON_PROCESSING', 'PATH_ORDERING', 'VALIDATION', 'POST_PROCESSING', 'ARTIFACT_PERSISTENCE', name='jobstage'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total_layers', sa.Integer(), nullable=True),
    sa.Column('mesh_filename', sa.String(length=255), nullable=False),
    sa.Column('mesh_format', sa.Enum('STL_BINARY', name='meshformat'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('layer_idx_min', sa.Integer(), nullable=False),
    sa.Column('layer_idx_max', sa.Integer(), nullable=False),
    sa.Column('min_z', sa.Float(), nullable=False),
    sa.Column('max_z', sa.Float(), nullable=False),
    sa.Column('validity', sa.Enum('PENDING', 'VALID', 'INVALID', 'EMPTY', 'PARTIAL', name='chunkvalidity'), nullable=False),
    sa.Column('triangle_count', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('layer_idx', sa.Integer(), nullable=False),
    sa.Column('z_height', sa.Float(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('is_planar', sa.Boolean(), nullable=False),
    sa.Column('is_support', sa.Boolean(), nullable=False),
    sa.Column('gcode_offset', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layers')
    op.drop_table('chunks')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
