"""diagnostics_f016

Revision ID: 5ab3716b47bf
Revises: 8e5dad8c3428
Create Date: 2026-09-10 23:14:13.262106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab3716b47bf'
down_revision: Union[str, Sequence[str], None] = '8e5dad8c3428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('layer_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Enum('MESH_VALIDATION', 'CANONICAL_FRAME', 'CHUNK_CONSTRUCTION', 'SECTIONING', 'POLYGON_PROCESSING', 'PATH_ORDERING', 'VALIDATION', 'POST_PROCESSING', 'ARTIFACT_PERSISTENCE', name='jobstage'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='diagnosticseverity'), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'WARNING', 'FAIL', 'NOT_IMPLEMENTED', name='diagnosticstatus'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.create_index('ix_diagnostics_job_id_severity_status', ['job_id', 'severity', 'status'], unique=False)
        batch_op.create_index('ix_diagnostics_job_id_stage', ['job_id', 'stage'], unique=False)

    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute('''
        CREATE TRIGGER chk_diag_chunk_job
        BEFORE INSERT ON diagnostics
        FOR EACH ROW
        WHEN NEW.chunk_id IS NOT NULL
        BEGIN
          SELECT RAISE(ABORT, 'Diagnostic chunk belongs to different job')
          WHERE (SELECT job_id FROM chunks WHERE id = NEW.chunk_id) != NEW.job_id;
        END;
        ''')

        op.execute('''
        CREATE TRIGGER chk_diag_layer_job
        BEFORE INSERT ON diagnostics
        FOR EACH ROW
        WHEN NEW.layer_id IS NOT NULL
        BEGIN
          SELECT RAISE(ABORT, 'Diagnostic layer belongs to different job')
          WHERE (SELECT job_id FROM layers WHERE id = NEW.layer_id) != NEW.job_id;
        END;
        ''')
    elif bind.dialect.name == "postgresql":
        op.execute('''
        CREATE OR REPLACE FUNCTION check_diag_chunk_job() RETURNS trigger AS $$
        BEGIN
            IF NEW.chunk_id IS NOT NULL THEN
                IF (SELECT job_id FROM chunks WHERE id = NEW.chunk_id) != NEW.job_id THEN
                    RAISE EXCEPTION 'Diagnostic chunk belongs to different job';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER chk_diag_chunk_job
        BEFORE INSERT ON diagnostics
        FOR EACH ROW
        EXECUTE FUNCTION check_diag_chunk_job();
        ''')

        op.execute('''
        CREATE OR REPLACE FUNCTION check_diag_layer_job() RETURNS trigger AS $$
        BEGIN
            IF NEW.layer_id IS NOT NULL THEN
                IF (SELECT job_id FROM layers WHERE id = NEW.layer_id) != NEW.job_id THEN
                    RAISE EXCEPTION 'Diagnostic layer belongs to different job';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER chk_diag_layer_job
        BEFORE INSERT ON diagnostics
        FOR EACH ROW
        EXECUTE FUNCTION check_diag_layer_job();
        ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute('DROP TRIGGER IF EXISTS chk_diag_layer_job;')
        op.execute('DROP TRIGGER IF EXISTS chk_diag_chunk_job;')
    elif bind.dialect.name == "postgresql":
        op.execute('DROP TRIGGER IF EXISTS chk_diag_layer_job ON diagnostics;')
        op.execute('DROP FUNCTION IF EXISTS check_diag_layer_job();')
        op.execute('DROP TRIGGER IF EXISTS chk_diag_chunk_job ON diagnostics;')
        op.execute('DROP FUNCTION IF EXISTS check_diag_chunk_job();')

    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.drop_index('ix_diagnostics_job_id_stage')
        batch_op.drop_index('ix_diagnostics_job_id_severity_status')

    op.drop_table('diagnostics')
    # ### end Alembic commands ###