"""f014_f015

Revision ID: 8e5dad8c3428
Revises: ed3259207f6b
Create Date: 2026-09-10 20:07:16.545043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5dad8c3428'
down_revision: Union[str, Sequence[str], None] = 'ed3259207f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_idx', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('source_plane', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('transform_matrix', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('last_completed_layer', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_job_chunk_idx', ['job_id', 'chunk_idx'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('mesh_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('machine_profile_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('engine_revision', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('input_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('checkpoint_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        
        batch_op.create_foreign_key('fk_jobs_creator_id', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_jobs_mesh_id', 'meshes', ['mesh_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_jobs_machine_profile_id', 'machine_profiles', ['machine_profile_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('current_stage')
        batch_op.drop_column('user_id')
        batch_op.drop_column('mesh_format')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('total_layers')
        batch_op.drop_column('mesh_filename')
        batch_op.drop_column('job_name')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('job_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('mesh_filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('total_layers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('mesh_format', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.CHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('current_stage', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('checkpoint_data')
        batch_op.drop_column('input_hash')
        batch_op.drop_column('engine_revision')
        batch_op.drop_column('settings')
        batch_op.drop_column('machine_profile_id')
        batch_op.drop_column('mesh_id')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_chunk_idx', type_='unique')
        batch_op.drop_column('last_completed_layer')
        batch_op.drop_column('transform_matrix')
        batch_op.drop_column('source_plane')
        batch_op.drop_column('chunk_idx')

    # uq_job_chunk_idx drop moved to schema_parity migration

    # ### end Alembic commands ###
