"""Add cleaned_up_at to Mesh and Export

Revision ID: ef62d4b56782
Revises: 188eaae3020d
Create Date: 2026-09-12 00:40:43.227657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ef62d4b56782'
down_revision: Union[str, Sequence[str], None] = '188eaae3020d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleaned_up_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('meshes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleaned_up_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meshes', schema=None) as batch_op:
        batch_op.drop_column('cleaned_up_at')

    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_column('cleaned_up_at')
    # ### end Alembic commands ###
